### ISSUE TITLE
CS5490 arduino connection

### ISSUE THREAD

**Issue by ErogluBaris** [tiagolobao/CS5490#10]
Hello, firstly i want to thank you for doing such useful library. We are trying to connect cs5490 to arduino and measure voltage values. We connect them with the typical connection diagram (https://statics.cirrus.com/pubs/proDatasheet/CS5490_F3.pdf -> page 55) from datasheet of CS5490. Since we are just trying to measure DC voltage value we didn't connect IIN+, IIN-, DO and RESET. We uploaded to arduino your On_Chip_Calibration.ino file. However we just see 0 value. So we think that we were just communicating with your library actually and never start CS5490 to operate. How can we measure voltage and how can we know that we are communicating with CS5490 because we couldn't figure it out.

Thanks again
Have a good day

**Comment by tiagolobao** [comment]
Hey! You're welcome. Thanks for using it. :)

1. I would recommend for you to try first the **CS5490_Basics** example, and se if it run ok (You should see something different than 0 if I'm not mistaken). I could not test the On_Chip_Calibration.ino example properly.
2. The RESET Pin is important. you can just not connect to the Arduino, but you need to put as HIGH (3.3v) The connection diagram do this by connecting through a up a pull-up resistor. The other ones can be unconnected
3. By default, the [TX pin when not transmitting should be at HIGH value](https://electronics.stackexchange.com/questions/78098/voltage-at-uart-tx-and-rx-pins-with-no-connections). So you can put some LED and see if it's turned on at least...
4. You can measure the DC Value using line.getPeakV, line.getInstV or line.getRmsV Depends on your application

Look at those topics, and if you still have problems we can.

**Comment by ErogluBaris** [comment]
Thanks a lot. I am goning to try them. And also thanks for the quick response :D

**Comment by ErogluBaris** [comment]
Hello again :D
We try to communicate with cs5490 but we failed again. We look for our possible mistakes and we found one:
https://forum.arduino.cc/index.php?topic=285870.msg2018368#msg2018368 -> here we connect rx tx pins to cs5490, but in this link they say you can't communicate cs5490 with rx and tx pins, because they are for serial communication with PC. So we define two different pins and we tried again. But we failed as well....
Also, from the code, you can see that we used reset pin as you said.
Furthermore, we are using Tisham Dhar's CS5490 breakout ( https://github.com/whatnick/CS5490_Breakout) and he said that ardiuno uno operates with 5V but cs5490 is 3.3V so you should use ESP8266 instead of arduino uno. And we are using it now. 
I share our codes and circuit diagram with zip file. There are two ino files, the one with ESP we used your library, and the other one (with arduino) we combine your withoutLib

_SS code(https://github.com/tiagolobao/CS5490/blob/master/examples/withoutLib_SS/withoutLib_SS.ino) and https://forum.arduino.cc/index.php?topic=285870.msg2018368#msg2018368 that link.
Please help us with this issue, we have no idea where we are making a mistake, the code or in the circuit.

Thanks for your help :D
[CS5490.zip](https://github.com/tiagolobao/CS5490/files/4638215/CS5490.zip)

**Comment by tiagolobao** [comment]
Hi! It was pretty hard for me to get the first response also, so don't give up hahaaha.
Hmmm ok. I don't know much about whatnick's breakout repo, so I'll focus on the esp/arduino code. 

Just FYI: And about using arduino. If you have ESP, better. For arduino I had to make some voltage dividers from 5v to 3.3v. About rx/tx pins, Yes, you need to avoid hardware serial pins (0,1 I think, not sure) That's why the library uses *Software Serial* when the board has only one *HardwareSerial* Interface.

I'll make another list with potential issues in your project.
1. You need to put this part here:  (I suppose pin 16 is the reset). Make sure that the RESET pin set to HIGH at every operation. I say this because there is "line.contConv();" before this piece of code that sets the pin 16 to high
```cpp
pinMode(16,OUTPUT);
digitalWrite(16,HIGH);
```
Maybe you can simplify this just connecting  the reset pin directly to 3.3v to guarantee the HIGH value independent of the arduino/ESP... dunno.
2. Which clock (crystal) you're using? the default value (the recommended in the datasheet) is 4.096Mhz
3. This print is only a repesentation of the circuit, or you used Proteus to simulate everything? I see that the rx (14) and tx (12) are according to the diagram, but defined pin 16 in the code that should be reset, is actually conected to the GPIO (18). You should change maybe?

I can't see any other issues there. O f course, I took a quick look. Tell me if you succeed


EDIT: being more explicit regarding number 1:
```cpp
void setup() {

  // Keep this here
  pinMode(16,OUTPUT);
  digitalWrite(16,HIGH);

  line.begin(600);
  Serial.begin(115200);
  while (!Serial);
  line.contConv();

  // Try with and without this part here
  digitalWrite(16,LOW);
  delay(2000);
  digitalWrite(16,HIGH);
}
```

**Comment by ErogluBaris** [comment]
Hello,

Finally we succeeded communicating with CS5490, so many thanks for your help. 

Now we are reading some values but there is something we couldn't understand right now. We are using calibration and firstly, we read 0V as 0.01174. Then, we read 3.3V(esp gives 3.45 as we measured with multimeter) as 0.02188. So if we consider DCOffset value, 3.3V is 
0.022188 - 0.01174 = 0.01014. But when we calculate our line voltage with voltage divider (this divider contains 1k and 1350k resistors) we should see 3.3*(1/1351) = 0.002442. But this value is so different from the value we read. 

So what is the problem here. Did we understand calibration wrong or something else has to be done? We need help.

**Comment by tiagolobao** [comment]
Awsome! :)

Ok, calibration now...
I have a whole conversation with a friend about some issue that seems close to yours. (Send me an email and I can forward everything to you) I can make a brief, but I can't do it right now.

I can't remember exactly what it was but I think you have to use line.rms or line.peak (even with DC voltage) this also depends on the convertion (single vs continuous) maybe the voltage Gain, etc...

**Comment by tiagolobao** [comment]
Since the communication part (that is library related) is solved. I'll close this issue.

**Comment by ErogluBaris** [comment]
Thank you very much again:D
