### ISSUE TITLE
CS5490 Energy Meter Circuit Design Questions

### ISSUE THREAD

**Issue by SafaKarip** [tiagolobao/CS5490#11]
Hello, firstly I would like to thank you for the library you created and post you shared on the energy meter you designed, you helped us a great deal with those. On to the topic, We are trying to create a smart plug much like yours and using cs5490 for the measurement part.
While trying to understand the board design you shared, I failed to understand a few points so I wanted to ask you about it,
![image](https://user-images.githubusercontent.com/52178503/82681984-35632800-9c57-11ea-9679-8eb6499d80da.png)

1-Voltage pins seem to have both ends on ground (N and ground), shouldn't one of them be on line(L)?
2-The ground you placed between R4 shunt resistor and F1 20A fuse, was it to protect the board in case there is no load or does it have another function that I could not comprehend 
3-When we measure voltage values we multiply it with a value based on the voltage divider. But for we do not know that how can we calculate the factor that is multiplied with current measurements. If we are using a 0.01-ohm shunt resistor, then how the calculation should be.

**Comment by tiagolobao** [comment]
Hello! Glad that you liked. So, to be honest, I took this image from [another project.](https://www.instructables.com/id/Smart-home-energy-management-system-SHEMMS/) The most complete one I found at least. take a look, it may have some other good info there.

I worked mainly in the software, that means that maybe I'm not the best person to be asked those questions, but since I'm also intersted I'll try to answer anyway!

1. Voltage pins you mean the voltage measure pins ( 6,7 )? or the CS5490 power supply ( 11, 10 )?

2. About the GND location next to shunt, here I have some explanation that Vytautas sent me some time ago and maybe can clarify a little bit:

> (I presume that you are using a shunt resistor for current sensing)
> 
> Layout and topology are extremely critical !
> The CS5490 circuitry must have its own isolated and independent ground (analog ground).
> No strong currents should ever circulate through the analog ground.
> The analog ground must be connected to the load circuit in a  SINGLE  point.
> The voltage divider's termination resistor and all input filter capacitors should be connected as close as possible to that point.
> That point should be the physical shunt terminal that is connected to the mains NEUTRAL.
> Keep the mains LINE as far as possible from the CS5490 circuitry.
> If practical, it's convenient to shield the input circuits from noise.
> 
> Consider the three cases shown in the figure.
> CASE 1
> It is the best solution. There is no common-mode voltage and the current sample is directly applied to the sense inputs.
> CASE 2
> The current sample is directly applied to the sense inputs,   but the CS5490 has to make an extra effort to get rid of the common-mode voltage and the final reading will depend on how well this job is done.
> CASE 3.
> The common-mode voltage disappears by connecting  I-  to B instead of A. The system behaves as if the shunt was larger (RS' = RS + RAB)
> The current reading will be greater than the actual current, but this could be corrected by reducing the Gain of the current channel.
> 
> There is however a catch in this "solution" :  A good quality shunt resistor retains its value (RS) over time and temperature changes, but the same cannot be said about the value of RAB and hence the current reading will depend on the stability of RAB.
>
>![Shunt](https://user-images.githubusercontent.com/15076325/82686814-1799c100-9c5f-11ea-9b64-28ec42239199.jpg)

3. The idea is: the 0.01 ohm shunt resistor gave you an output of instant +250mV (for example) 
if you look the datasheet:
> 6.6.30  Instantaneous Current (I) – Page 16, Address 2
> value in the range of -1.0 > value >1.0
and
![image](https://user-images.githubusercontent.com/15076325/82690008-1ae37b80-9c64-11ea-8bd5-80248f0f7920.png)

It means that (If the I gain is 10) the current should be V = R*I that is 250mV = 0.01Ohm * I that is I = 25A 

Or you can measure the current with something else, take the values, compare with CS5490 values and calibrate using those numbers. Ex: 1A -> 0.10 and 2A -> 0.20 means you should do something like this:
```cpp
double instantI =  line.getInstV();
Serial.print(" The current is: ");
Serial.println( instantI * 10 );
```

PS: I cant remember right now if the output 1 means exactly 250mV with gain 10, or if there is any other remaks.

**Comment by tiagolobao** [comment]
Issue closed. Assuming problem is solved
